# This file is generated by D:\Dev\Compile\scipy\scipy-0.11\setup.py
# It contains system_info results at the time of building this package.
__all__ = ["get_info","show"]

amd_info={'libraries': ['amd'], 'library_dirs': ['D:\\Dev\\Compile\\inclib-x64'], 'swig_opts': ['-ID:\\Dev\\Compile\\inclib-x64'], 'define_macros': [('SCIPY_AMD_H', None)], 'include_dirs': ['D:\\Dev\\Compile\\inclib-x64']}
lapack_opt_info={'libraries': ['mkl_lapack95_lp64', 'mkl_blas95_lp64', 'mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'libiomp5md', 'libifportmd', 'mkl_lapack95_lp64', 'mkl_blas95_lp64', 'mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'libiomp5md', 'libifportmd'], 'library_dirs': ['C:/Program Files (x86)/Intel/Compiler/11.1/070/mkl/em64t/lib'], 'define_macros': [('SCIPY_MKL_H', None)], 'include_dirs': ['C:/Program Files (x86)/Intel/Compiler/11.1/070/mkl/include']}
blas_opt_info={'libraries': ['mkl_lapack95_lp64', 'mkl_blas95_lp64', 'mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'libiomp5md', 'libifportmd'], 'library_dirs': ['C:/Program Files (x86)/Intel/Compiler/11.1/070/mkl/em64t/lib'], 'define_macros': [('SCIPY_MKL_H', None)], 'include_dirs': ['C:/Program Files (x86)/Intel/Compiler/11.1/070/mkl/include']}
umfpack_info={'libraries': ['umfpack', 'amd'], 'library_dirs': ['D:\\Dev\\Compile\\inclib-x64'], 'swig_opts': ['-ID:\\Dev\\Compile\\inclib-x64\\umfpack', '-ID:\\Dev\\Compile\\inclib-x64'], 'define_macros': [('SCIPY_UMFPACK_H', None), ('SCIPY_AMD_H', None)], 'include_dirs': ['D:\\Dev\\Compile\\inclib-x64\\umfpack', 'D:\\Dev\\Compile\\inclib-x64']}
lapack_mkl_info={'libraries': ['mkl_lapack95_lp64', 'mkl_blas95_lp64', 'mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'libiomp5md', 'libifportmd', 'mkl_lapack95_lp64', 'mkl_blas95_lp64', 'mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'libiomp5md', 'libifportmd'], 'library_dirs': ['C:/Program Files (x86)/Intel/Compiler/11.1/070/mkl/em64t/lib'], 'define_macros': [('SCIPY_MKL_H', None)], 'include_dirs': ['C:/Program Files (x86)/Intel/Compiler/11.1/070/mkl/include']}
blas_mkl_info={'libraries': ['mkl_lapack95_lp64', 'mkl_blas95_lp64', 'mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'libiomp5md', 'libifportmd'], 'library_dirs': ['C:/Program Files (x86)/Intel/Compiler/11.1/070/mkl/em64t/lib'], 'define_macros': [('SCIPY_MKL_H', None)], 'include_dirs': ['C:/Program Files (x86)/Intel/Compiler/11.1/070/mkl/include']}
mkl_info={'libraries': ['mkl_lapack95_lp64', 'mkl_blas95_lp64', 'mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'libiomp5md', 'libifportmd'], 'library_dirs': ['C:/Program Files (x86)/Intel/Compiler/11.1/070/mkl/em64t/lib'], 'define_macros': [('SCIPY_MKL_H', None)], 'include_dirs': ['C:/Program Files (x86)/Intel/Compiler/11.1/070/mkl/include']}

def get_info(name):
    g = globals()
    return g.get(name, g.get(name + "_info", {}))

def show():
    for name,info_dict in globals().items():
        if name[0] == "_" or type(info_dict) is not type({}): continue
        print(name + ":")
        if not info_dict:
            print("  NOT AVAILABLE")
        for k,v in info_dict.items():
            v = str(v)
            if k == "sources" and len(v) > 200:
                v = v[:60] + " ...\n... " + v[-60:]
            print("    %s = %s" % (k,v))
    